name: Update Portfolio Analysis

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ main ]
    paths-ignore:    # Ignore les changements sur ces fichiers
      - 'PORTFOLIO.md'
      - 'github_portfolio.json'
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Check directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory content:"
          ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt --no-cache-dir
          python -m pip list

      - name: Run analysis
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) python analyze.py
          
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update portfolio analysis [skip ci]" && git push)